version: '3.7'
services:
  frontend:
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
  backend:
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
  db:
    ports:
      - "5432:5432"